//go:build ignore

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"
)

const (
	// Adguard filter rules, one of the most comprehensive
	filterURL  = "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt"
	outputFile = "tracking_params_gen.go"
)

// simpleRule matches lines like "$removeparam=param_name" with no extra modifiers.
var simpleRule = regexp.MustCompile(`^\$removeparam=([a-zA-Z0-9_\-]+)$`)

func main() {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(filterURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to fetch filter list: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Fprintf(os.Stderr, "unexpected status code: %d\n", resp.StatusCode)
		os.Exit(1)
	}

	seen := make(map[string]struct{})
	scanner := bufio.NewScanner(resp.Body)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if m := simpleRule.FindStringSubmatch(line); m != nil {
			seen[strings.ToLower(m[1])] = struct{}{}
		}
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "error reading response: %v\n", err)
		os.Exit(1)
	}

	params := make([]string, 0, len(seen))
	for p := range seen {
		params = append(params, p)
	}
	sort.Strings(params)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gen_tracking_params.go; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Source: %s\n\n", filterURL)
	fmt.Fprintf(&buf, "package urlutil\n\n")
	fmt.Fprintf(&buf, "var trackingParams = map[string]struct{}{\n")
	for _, p := range params {
		fmt.Fprintf(&buf, "\t%q: {},\n", p)
	}
	fmt.Fprintf(&buf, "}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to format generated code: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d tracking parameters\n", outputFile, len(params))
}
