services:
  kratos-migrate:
    image: oryd/kratos:v25.4.0
    command: "-c /etc/config/kratos/kratos.yml migrate sql -e --yes"
    restart: on-failure
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    environment:
      - DSN=${KRATOS_DSN}
    networks:
      - intranet

  kratos:
    image: oryd/kratos:v25.4.0
    depends_on:
      - kratos-migrate
    command: "-c /etc/config/kratos/kratos.yml serve --dev --watch-courier"
    restart: unless-stopped
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    environment:
      - DSN=${KRATOS_DSN}
      - LOG_LEVEL=trace
    networks:
      - intranet
    healthcheck:
      test: ["CMD", "kratos", "remote", "status", "-e", "http://localhost:4434"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 1s

  scraper:
    build:
      context: ../scraper
      dockerfile: Dockerfile
    restart: on-failure:5
    depends_on:
      redis: { condition: service_healthy }
    environment:
      SCRAPER_REDIS_URL: redis://redis:6379/0
      SCRAPER_STREAM_INPUT: scrape:jobs
      SCRAPER_STREAM_OUTPUT: scrape:results
      SCRAPER_CONSUMER_GROUP: scraper-group
      SCRAPER_CONSUMER_NAME: scraper-1
      SCRAPER_BLOCK_MS: ${SCRAPER_BLOCK_MS}
      SCRAPER_MAX_WORKERS: ${SCRAPER_MAX_WORKERS}
      SCRAPER_MAX_RETRIES: ${SCRAPER_MAX_RETRIES}
      SCRAPER_MIN_IDLE_TIME: ${SCRAPER_MIN_IDLE_TIME}
    networks:
      - intranet

  phonemizer:
    build:
      context: ../phonemizer
      dockerfile: Dockerfile
    restart: on-failure:5
    depends_on:
      redis: { condition: service_healthy }
    environment:
      PHONEMIZER_REDIS_URL: redis://redis:6379/0
      PHONEMIZER_STREAM_INPUT: scrape:results
      PHONEMIZER_STREAM_OUTPUT: phonemize:results
      PHONEMIZER_CONSUMER_GROUP: phonemizer-group
      PHONEMIZER_CONSUMER_NAME: phonemizer-1
      PHONEMIZER_BLOCK_MS: ${PHONEMIZER_BLOCK_MS}
      PHONEMIZER_MAX_RETRIES: ${PHONEMIZER_MAX_RETRIES}
      PHONEMIZER_MIN_IDLE_TIME: ${PHONEMIZER_MIN_IDLE_TIME}
    networks:
      - intranet

  bff:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: on-failure:5
    depends_on:
      redis: { condition: service_healthy }
      postgres: { condition: service_healthy }
      kratos: { condition: service_healthy }
    ports:
      - "${BFF_PORT}:${BFF_PORT}"
    environment:
      ENVIRONMENT: dev
      PORT: ${BFF_PORT}
      KRATOS_PUBLIC_URL: http://kratos:4433
      DATABASE_CONFIG_HOSTNAME: postgres
      DATABASE_CONFIG_PORT: ${POSTGRES_PORT}
      DATABASE_CONFIG_USERNAME: ${BFF_POSTGRES_USER}
      DATABASE_CONFIG_PASSWORD: ${BFF_POSTGRES_PASSWORD}
      DATABASE_CONFIG_DATABASE: ${BFF_POSTGRES_DB}
      DATABASE_CONFIG_SSLMODE: disable
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      REDIS_GROUP_NAME: ${BFF_REDIS_GROUP_NAME}
      REDIS_CONSUMER_NAME: ${BFF_REDIS_CONSUMER_NAME}
    networks:
      - intranet

  redis:
    image: redis:8-alpine
    ports: ["${REDIS_PORT}:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - intranet

  postgres:
    image: postgres:16-alpine
    user: postgres
    restart: always
    shm_size: 1024m
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        read_only: false
      - type: bind
        source: ./database/pg_hba.conf
        target: /etc/postgresql/pg_hba.conf
      - type: bind
        source: ./database/docker-initdb
        target: /docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - KRATOS_POSTGRES_PASSWORD=${KRATOS_POSTGRES_PASSWORD}
      - BFF_POSTGRES_PASSWORD=${BFF_POSTGRES_PASSWORD}
    networks:
      - intranet
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "localhost",
          "-p",
          "${POSTGRES_PORT}",
          "-U",
          "${POSTGRES_ADMIN_USER}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
networks:
  intranet:
