// Mocks generated by Mockito 5.4.6 from annotations
// in readintent_flutter/test/articles/providers/articles_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:readintent_flutter/features/articles/repository/article_repository.dart'
    as _i3;
import 'package:readintent_flutter/proto/articles/v1/articles_service.pb.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetArticlesResponse_0 extends _i1.SmartFake
    implements _i2.GetArticlesResponse {
  _FakeGetArticlesResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeParseArticleResult_1 extends _i1.SmartFake
    implements _i3.ParseArticleResult {
  _FakeParseArticleResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ArticleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRepository extends _i1.Mock implements _i3.ArticleRepository {
  MockArticleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GetArticlesResponse> getArticles({
    int? pageSize = 20,
    void Function(_i2.GetArticlesResponse)? onUpdated,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getArticles, [], {
              #pageSize: pageSize,
              #onUpdated: onUpdated,
            }),
            returnValue: _i4.Future<_i2.GetArticlesResponse>.value(
              _FakeGetArticlesResponse_0(
                this,
                Invocation.method(#getArticles, [], {
                  #pageSize: pageSize,
                  #onUpdated: onUpdated,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.GetArticlesResponse>);

  @override
  _i4.Future<_i2.GetArticlesResponse> getArticlesPage({
    int? pageSize = 20,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getArticlesPage, [], {
              #pageSize: pageSize,
              #pageToken: pageToken,
            }),
            returnValue: _i4.Future<_i2.GetArticlesResponse>.value(
              _FakeGetArticlesResponse_0(
                this,
                Invocation.method(#getArticlesPage, [], {
                  #pageSize: pageSize,
                  #pageToken: pageToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.GetArticlesResponse>);

  @override
  _i4.Future<_i2.Article?> getArticle(
    String? id, {
    void Function(_i2.Article)? onUpdated,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getArticle, [id], {#onUpdated: onUpdated}),
            returnValue: _i4.Future<_i2.Article?>.value(),
          )
          as _i4.Future<_i2.Article?>);

  @override
  _i4.Future<_i3.ParseArticleResult> parseArticle(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#parseArticle, [url]),
            returnValue: _i4.Future<_i3.ParseArticleResult>.value(
              _FakeParseArticleResult_1(
                this,
                Invocation.method(#parseArticle, [url]),
              ),
            ),
          )
          as _i4.Future<_i3.ParseArticleResult>);

  @override
  _i4.Future<void> deleteArticle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteArticle, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
