-- Users table migration
-- The id store the ID generated by the authentication provider (Kratos)
-- Additional fields can be added as needed, but no use currently
-- +goose Up
CREATE TABLE users (
    id varchar PRIMARY KEY
);

-- +goose Down
DROP TABLE users;