-- Users table migration
-- The id store the ID generated by the authentication provider (Kratos)
-- Additional fields can be added as needed, but no use currently
-- +goose Up
BEGIN;
CREATE TABLE users (
    id varchar PRIMARY KEY
);
COMMIT;

-- +goose Down
BEGIN;
DROP TABLE users;
COMMIT;