// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: articles/v1/articles_service.proto

package articlesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhonemizerTokenMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	PhonemeLen    uint32                 `protobuf:"varint,2,opt,name=phoneme_len,json=phonemeLen,proto3" json:"phoneme_len,omitempty"`
	HasWhitespace bool                   `protobuf:"varint,3,opt,name=has_whitespace,json=hasWhitespace,proto3" json:"has_whitespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhonemizerTokenMeta) Reset() {
	*x = PhonemizerTokenMeta{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhonemizerTokenMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhonemizerTokenMeta) ProtoMessage() {}

func (x *PhonemizerTokenMeta) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhonemizerTokenMeta.ProtoReflect.Descriptor instead.
func (*PhonemizerTokenMeta) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{0}
}

func (x *PhonemizerTokenMeta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PhonemizerTokenMeta) GetPhonemeLen() uint32 {
	if x != nil {
		return x.PhonemeLen
	}
	return 0
}

func (x *PhonemizerTokenMeta) GetHasWhitespace() bool {
	if x != nil {
		return x.HasWhitespace
	}
	return false
}

type PhonemizerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graphemes     string                 `protobuf:"bytes,1,opt,name=graphemes,proto3" json:"graphemes,omitempty"`
	Phonemes      string                 `protobuf:"bytes,2,opt,name=phonemes,proto3" json:"phonemes,omitempty"`
	TokenIds      []int64                `protobuf:"varint,3,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
	TokenMeta     []*PhonemizerTokenMeta `protobuf:"bytes,4,rep,name=token_meta,json=tokenMeta,proto3" json:"token_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhonemizerData) Reset() {
	*x = PhonemizerData{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhonemizerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhonemizerData) ProtoMessage() {}

func (x *PhonemizerData) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhonemizerData.ProtoReflect.Descriptor instead.
func (*PhonemizerData) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{1}
}

func (x *PhonemizerData) GetGraphemes() string {
	if x != nil {
		return x.Graphemes
	}
	return ""
}

func (x *PhonemizerData) GetPhonemes() string {
	if x != nil {
		return x.Phonemes
	}
	return ""
}

func (x *PhonemizerData) GetTokenIds() []int64 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *PhonemizerData) GetTokenMeta() []*PhonemizerTokenMeta {
	if x != nil {
		return x.TokenMeta
	}
	return nil
}

type ArticlePreview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// failed, processing, text_ready, ready
	Status     string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Title      string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author     string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Date       string   `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Url        string   `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Categories []string `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	// If the description failed to be extracted from the metadata,
	// we should add put the first few hundred characters in
	Description   *string `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Image         *string `protobuf:"bytes,9,opt,name=image,proto3,oneof" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticlePreview) Reset() {
	*x = ArticlePreview{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlePreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlePreview) ProtoMessage() {}

func (x *ArticlePreview) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlePreview.ProtoReflect.Descriptor instead.
func (*ArticlePreview) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{2}
}

func (x *ArticlePreview) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticlePreview) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ArticlePreview) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticlePreview) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ArticlePreview) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ArticlePreview) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ArticlePreview) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ArticlePreview) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ArticlePreview) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

// Full article with all content
type Article struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// failed, started_gathering, text_ready, ready
	Status         string          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Title          string          `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author         string          `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Date           string          `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	ExtractedHtml  string          `protobuf:"bytes,6,opt,name=extracted_html,json=extractedHtml,proto3" json:"extracted_html,omitempty"`
	PureText       string          `protobuf:"bytes,7,opt,name=pure_text,json=pureText,proto3" json:"pure_text,omitempty"`
	Url            string          `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	Categories     []string        `protobuf:"bytes,9,rep,name=categories,proto3" json:"categories,omitempty"`
	Description    *string         `protobuf:"bytes,10,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Image          *string         `protobuf:"bytes,11,opt,name=image,proto3,oneof" json:"image,omitempty"`
	PhonemizerData *PhonemizerData `protobuf:"bytes,12,opt,name=phonemizer_data,json=phonemizerData,proto3,oneof" json:"phonemizer_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{3}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Article) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Article) GetExtractedHtml() string {
	if x != nil {
		return x.ExtractedHtml
	}
	return ""
}

func (x *Article) GetPureText() string {
	if x != nil {
		return x.PureText
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Article) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Article) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *Article) GetPhonemizerData() *PhonemizerData {
	if x != nil {
		return x.PhonemizerData
	}
	return nil
}

type GetArticlesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filters
	Categories    []string `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	SearchQuery   *string  `protobuf:"bytes,4,opt,name=search_query,json=searchQuery,proto3,oneof" json:"search_query,omitempty"`
	Author        *string  `protobuf:"bytes,5,opt,name=author,proto3,oneof" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesRequest) Reset() {
	*x = GetArticlesRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesRequest) ProtoMessage() {}

func (x *GetArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetArticlesRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticlesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetArticlesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetArticlesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetArticlesRequest) GetSearchQuery() string {
	if x != nil && x.SearchQuery != nil {
		return *x.SearchQuery
	}
	return ""
}

func (x *GetArticlesRequest) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

type GetArticlesResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Articles []*ArticlePreview      `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	// Token for the cursor based pagination
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of articles matching the query
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesResponse) Reset() {
	*x = GetArticlesResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesResponse) ProtoMessage() {}

func (x *GetArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetArticlesResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetArticlesResponse) GetArticles() []*ArticlePreview {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *GetArticlesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetArticlesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ParseArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseArticleRequest) Reset() {
	*x = ParseArticleRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseArticleRequest) ProtoMessage() {}

func (x *ParseArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseArticleRequest.ProtoReflect.Descriptor instead.
func (*ParseArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{8}
}

func (x *ParseArticleRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ParseArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseArticleResponse) Reset() {
	*x = ParseArticleResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseArticleResponse) ProtoMessage() {}

func (x *ParseArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseArticleResponse.ProtoReflect.Descriptor instead.
func (*ParseArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{9}
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{11}
}

var File_articles_v1_articles_service_proto protoreflect.FileDescriptor

const file_articles_v1_articles_service_proto_rawDesc = "" +
	"\n" +
	"\"articles/v1/articles_service.proto\x12\varticles.v1\"q\n" +
	"\x13PhonemizerTokenMeta\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vphoneme_len\x18\x02 \x01(\rR\n" +
	"phonemeLen\x12%\n" +
	"\x0ehas_whitespace\x18\x03 \x01(\bR\rhasWhitespace\"\xa8\x01\n" +
	"\x0ePhonemizerData\x12\x1c\n" +
	"\tgraphemes\x18\x01 \x01(\tR\tgraphemes\x12\x1a\n" +
	"\bphonemes\x18\x02 \x01(\tR\bphonemes\x12\x1b\n" +
	"\ttoken_ids\x18\x03 \x03(\x03R\btokenIds\x12?\n" +
	"\n" +
	"token_meta\x18\x04 \x03(\v2 .articles.v1.PhonemizerTokenMetaR\ttokenMeta\"\x88\x02\n" +
	"\x0eArticlePreview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12%\n" +
	"\vdescription\x18\b \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\t \x01(\tH\x01R\x05image\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_image\"\xa4\x03\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12%\n" +
	"\x0eextracted_html\x18\x06 \x01(\tR\rextractedHtml\x12\x1b\n" +
	"\tpure_text\x18\a \x01(\tR\bpureText\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"categories\x18\t \x03(\tR\n" +
	"categories\x12%\n" +
	"\vdescription\x18\n" +
	" \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\v \x01(\tH\x01R\x05image\x88\x01\x01\x12I\n" +
	"\x0fphonemizer_data\x18\f \x01(\v2\x1b.articles.v1.PhonemizerDataH\x02R\x0ephonemizerData\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_imageB\x12\n" +
	"\x10_phonemizer_data\"\xd1\x01\n" +
	"\x12GetArticlesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12&\n" +
	"\fsearch_query\x18\x04 \x01(\tH\x00R\vsearchQuery\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x05 \x01(\tH\x01R\x06author\x88\x01\x01B\x0f\n" +
	"\r_search_queryB\t\n" +
	"\a_author\"\x97\x01\n" +
	"\x13GetArticlesResponse\x127\n" +
	"\barticles\x18\x01 \x03(\v2\x1b.articles.v1.ArticlePreviewR\barticles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x12GetArticleResponse\x12.\n" +
	"\aarticle\x18\x01 \x01(\v2\x14.articles.v1.ArticleR\aarticle\"'\n" +
	"\x13ParseArticleRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x16\n" +
	"\x14ParseArticleResponse\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteArticleResponse2\xdf\x02\n" +
	"\x0fArticlesService\x12S\n" +
	"\fParseArticle\x12 .articles.v1.ParseArticleRequest\x1a!.articles.v1.ParseArticleResponse\x12P\n" +
	"\vGetArticles\x12\x1f.articles.v1.GetArticlesRequest\x1a .articles.v1.GetArticlesResponse\x12M\n" +
	"\n" +
	"GetArticle\x12\x1e.articles.v1.GetArticleRequest\x1a\x1f.articles.v1.GetArticleResponse\x12V\n" +
	"\rDeleteArticle\x12!.articles.v1.DeleteArticleRequest\x1a\".articles.v1.DeleteArticleResponseBGZEgithub.com/gogotchuri/readintent/backend/proto/articles/v1;articlesv1b\x06proto3"

var (
	file_articles_v1_articles_service_proto_rawDescOnce sync.Once
	file_articles_v1_articles_service_proto_rawDescData []byte
)

func file_articles_v1_articles_service_proto_rawDescGZIP() []byte {
	file_articles_v1_articles_service_proto_rawDescOnce.Do(func() {
		file_articles_v1_articles_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articles_v1_articles_service_proto_rawDesc), len(file_articles_v1_articles_service_proto_rawDesc)))
	})
	return file_articles_v1_articles_service_proto_rawDescData
}

var file_articles_v1_articles_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_articles_v1_articles_service_proto_goTypes = []any{
	(*PhonemizerTokenMeta)(nil),   // 0: articles.v1.PhonemizerTokenMeta
	(*PhonemizerData)(nil),        // 1: articles.v1.PhonemizerData
	(*ArticlePreview)(nil),        // 2: articles.v1.ArticlePreview
	(*Article)(nil),               // 3: articles.v1.Article
	(*GetArticlesRequest)(nil),    // 4: articles.v1.GetArticlesRequest
	(*GetArticlesResponse)(nil),   // 5: articles.v1.GetArticlesResponse
	(*GetArticleRequest)(nil),     // 6: articles.v1.GetArticleRequest
	(*GetArticleResponse)(nil),    // 7: articles.v1.GetArticleResponse
	(*ParseArticleRequest)(nil),   // 8: articles.v1.ParseArticleRequest
	(*ParseArticleResponse)(nil),  // 9: articles.v1.ParseArticleResponse
	(*DeleteArticleRequest)(nil),  // 10: articles.v1.DeleteArticleRequest
	(*DeleteArticleResponse)(nil), // 11: articles.v1.DeleteArticleResponse
}
var file_articles_v1_articles_service_proto_depIdxs = []int32{
	0,  // 0: articles.v1.PhonemizerData.token_meta:type_name -> articles.v1.PhonemizerTokenMeta
	1,  // 1: articles.v1.Article.phonemizer_data:type_name -> articles.v1.PhonemizerData
	2,  // 2: articles.v1.GetArticlesResponse.articles:type_name -> articles.v1.ArticlePreview
	3,  // 3: articles.v1.GetArticleResponse.article:type_name -> articles.v1.Article
	8,  // 4: articles.v1.ArticlesService.ParseArticle:input_type -> articles.v1.ParseArticleRequest
	4,  // 5: articles.v1.ArticlesService.GetArticles:input_type -> articles.v1.GetArticlesRequest
	6,  // 6: articles.v1.ArticlesService.GetArticle:input_type -> articles.v1.GetArticleRequest
	10, // 7: articles.v1.ArticlesService.DeleteArticle:input_type -> articles.v1.DeleteArticleRequest
	9,  // 8: articles.v1.ArticlesService.ParseArticle:output_type -> articles.v1.ParseArticleResponse
	5,  // 9: articles.v1.ArticlesService.GetArticles:output_type -> articles.v1.GetArticlesResponse
	7,  // 10: articles.v1.ArticlesService.GetArticle:output_type -> articles.v1.GetArticleResponse
	11, // 11: articles.v1.ArticlesService.DeleteArticle:output_type -> articles.v1.DeleteArticleResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_articles_v1_articles_service_proto_init() }
func file_articles_v1_articles_service_proto_init() {
	if File_articles_v1_articles_service_proto != nil {
		return
	}
	file_articles_v1_articles_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_articles_v1_articles_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_articles_v1_articles_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articles_v1_articles_service_proto_rawDesc), len(file_articles_v1_articles_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_articles_v1_articles_service_proto_goTypes,
		DependencyIndexes: file_articles_v1_articles_service_proto_depIdxs,
		MessageInfos:      file_articles_v1_articles_service_proto_msgTypes,
	}.Build()
	File_articles_v1_articles_service_proto = out.File
	file_articles_v1_articles_service_proto_goTypes = nil
	file_articles_v1_articles_service_proto_depIdxs = nil
}
