// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: articles/v1/articles_service.proto

package articlesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Which list an article lives in. inbox and archive are mutually exclusive;
// favorite is an orthogonal flag (see is_favorite), not part of this enum.
type ArticleListState int32

const (
	ArticleListState_ARTICLE_LIST_STATE_UNSPECIFIED ArticleListState = 0 // treated as inbox
	ArticleListState_ARTICLE_LIST_STATE_INBOX       ArticleListState = 1
	ArticleListState_ARTICLE_LIST_STATE_ARCHIVE     ArticleListState = 2
)

// Enum value maps for ArticleListState.
var (
	ArticleListState_name = map[int32]string{
		0: "ARTICLE_LIST_STATE_UNSPECIFIED",
		1: "ARTICLE_LIST_STATE_INBOX",
		2: "ARTICLE_LIST_STATE_ARCHIVE",
	}
	ArticleListState_value = map[string]int32{
		"ARTICLE_LIST_STATE_UNSPECIFIED": 0,
		"ARTICLE_LIST_STATE_INBOX":       1,
		"ARTICLE_LIST_STATE_ARCHIVE":     2,
	}
)

func (x ArticleListState) Enum() *ArticleListState {
	p := new(ArticleListState)
	*p = x
	return p
}

func (x ArticleListState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleListState) Descriptor() protoreflect.EnumDescriptor {
	return file_articles_v1_articles_service_proto_enumTypes[0].Descriptor()
}

func (ArticleListState) Type() protoreflect.EnumType {
	return &file_articles_v1_articles_service_proto_enumTypes[0]
}

func (x ArticleListState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleListState.Descriptor instead.
func (ArticleListState) EnumDescriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{0}
}

// The view a GetArticles call is filtering for. favorite spans both inbox and
// archive (any article with is_favorite set).
type ArticleView int32

const (
	ArticleView_ARTICLE_VIEW_UNSPECIFIED ArticleView = 0 // defaults to inbox
	ArticleView_ARTICLE_VIEW_INBOX       ArticleView = 1
	ArticleView_ARTICLE_VIEW_FAVORITE    ArticleView = 2
	ArticleView_ARTICLE_VIEW_ARCHIVE     ArticleView = 3
)

// Enum value maps for ArticleView.
var (
	ArticleView_name = map[int32]string{
		0: "ARTICLE_VIEW_UNSPECIFIED",
		1: "ARTICLE_VIEW_INBOX",
		2: "ARTICLE_VIEW_FAVORITE",
		3: "ARTICLE_VIEW_ARCHIVE",
	}
	ArticleView_value = map[string]int32{
		"ARTICLE_VIEW_UNSPECIFIED": 0,
		"ARTICLE_VIEW_INBOX":       1,
		"ARTICLE_VIEW_FAVORITE":    2,
		"ARTICLE_VIEW_ARCHIVE":     3,
	}
)

func (x ArticleView) Enum() *ArticleView {
	p := new(ArticleView)
	*p = x
	return p
}

func (x ArticleView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleView) Descriptor() protoreflect.EnumDescriptor {
	return file_articles_v1_articles_service_proto_enumTypes[1].Descriptor()
}

func (ArticleView) Type() protoreflect.EnumType {
	return &file_articles_v1_articles_service_proto_enumTypes[1]
}

func (x ArticleView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleView.Descriptor instead.
func (ArticleView) EnumDescriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{1}
}

type PhonemizerTokenMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	PhonemeLen    uint32                 `protobuf:"varint,2,opt,name=phoneme_len,json=phonemeLen,proto3" json:"phoneme_len,omitempty"`
	HasWhitespace bool                   `protobuf:"varint,3,opt,name=has_whitespace,json=hasWhitespace,proto3" json:"has_whitespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhonemizerTokenMeta) Reset() {
	*x = PhonemizerTokenMeta{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhonemizerTokenMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhonemizerTokenMeta) ProtoMessage() {}

func (x *PhonemizerTokenMeta) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhonemizerTokenMeta.ProtoReflect.Descriptor instead.
func (*PhonemizerTokenMeta) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{0}
}

func (x *PhonemizerTokenMeta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PhonemizerTokenMeta) GetPhonemeLen() uint32 {
	if x != nil {
		return x.PhonemeLen
	}
	return 0
}

func (x *PhonemizerTokenMeta) GetHasWhitespace() bool {
	if x != nil {
		return x.HasWhitespace
	}
	return false
}

type PhonemizerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graphemes     string                 `protobuf:"bytes,1,opt,name=graphemes,proto3" json:"graphemes,omitempty"`
	Phonemes      string                 `protobuf:"bytes,2,opt,name=phonemes,proto3" json:"phonemes,omitempty"`
	TokenIds      []int64                `protobuf:"varint,3,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
	TokenMeta     []*PhonemizerTokenMeta `protobuf:"bytes,4,rep,name=token_meta,json=tokenMeta,proto3" json:"token_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhonemizerData) Reset() {
	*x = PhonemizerData{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhonemizerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhonemizerData) ProtoMessage() {}

func (x *PhonemizerData) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhonemizerData.ProtoReflect.Descriptor instead.
func (*PhonemizerData) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{1}
}

func (x *PhonemizerData) GetGraphemes() string {
	if x != nil {
		return x.Graphemes
	}
	return ""
}

func (x *PhonemizerData) GetPhonemes() string {
	if x != nil {
		return x.Phonemes
	}
	return ""
}

func (x *PhonemizerData) GetTokenIds() []int64 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *PhonemizerData) GetTokenMeta() []*PhonemizerTokenMeta {
	if x != nil {
		return x.TokenMeta
	}
	return nil
}

type ArticlePreview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// failed, processing, text_ready, ready
	Status     string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Title      string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author     string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Date       string   `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Url        string   `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Categories []string `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	// If the description failed to be extracted from the metadata,
	// we should add put the first few hundred characters in
	Description      *string          `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Image            *string          `protobuf:"bytes,9,opt,name=image,proto3,oneof" json:"image,omitempty"`
	PlayerPositionMs int64            `protobuf:"varint,10,opt,name=player_position_ms,json=playerPositionMs,proto3" json:"player_position_ms,omitempty"`
	ScrollPosition   float64          `protobuf:"fixed64,11,opt,name=scroll_position,json=scrollPosition,proto3" json:"scroll_position,omitempty"`
	ListState        ArticleListState `protobuf:"varint,12,opt,name=list_state,json=listState,proto3,enum=articles.v1.ArticleListState" json:"list_state,omitempty"`
	IsFavorite       bool             `protobuf:"varint,13,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ArticlePreview) Reset() {
	*x = ArticlePreview{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlePreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlePreview) ProtoMessage() {}

func (x *ArticlePreview) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlePreview.ProtoReflect.Descriptor instead.
func (*ArticlePreview) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{2}
}

func (x *ArticlePreview) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticlePreview) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ArticlePreview) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticlePreview) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ArticlePreview) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ArticlePreview) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ArticlePreview) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ArticlePreview) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ArticlePreview) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *ArticlePreview) GetPlayerPositionMs() int64 {
	if x != nil {
		return x.PlayerPositionMs
	}
	return 0
}

func (x *ArticlePreview) GetScrollPosition() float64 {
	if x != nil {
		return x.ScrollPosition
	}
	return 0
}

func (x *ArticlePreview) GetListState() ArticleListState {
	if x != nil {
		return x.ListState
	}
	return ArticleListState_ARTICLE_LIST_STATE_UNSPECIFIED
}

func (x *ArticlePreview) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

// Full article with all content
type Article struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// failed, started_gathering, text_ready, ready
	Status           string            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Title            string            `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author           string            `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Date             string            `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	ExtractedHtml    string            `protobuf:"bytes,6,opt,name=extracted_html,json=extractedHtml,proto3" json:"extracted_html,omitempty"`
	PureText         string            `protobuf:"bytes,7,opt,name=pure_text,json=pureText,proto3" json:"pure_text,omitempty"`
	Url              string            `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	Categories       []string          `protobuf:"bytes,9,rep,name=categories,proto3" json:"categories,omitempty"`
	Description      *string           `protobuf:"bytes,10,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Image            *string           `protobuf:"bytes,11,opt,name=image,proto3,oneof" json:"image,omitempty"`
	PhonemizerData   []*PhonemizerData `protobuf:"bytes,12,rep,name=phonemizer_data,json=phonemizerData,proto3" json:"phonemizer_data,omitempty"`
	PlayerPositionMs int64             `protobuf:"varint,13,opt,name=player_position_ms,json=playerPositionMs,proto3" json:"player_position_ms,omitempty"`
	ScrollPosition   float64           `protobuf:"fixed64,14,opt,name=scroll_position,json=scrollPosition,proto3" json:"scroll_position,omitempty"`
	PlaybackSpeed    float64           `protobuf:"fixed64,15,opt,name=playback_speed,json=playbackSpeed,proto3" json:"playback_speed,omitempty"`
	ListState        ArticleListState  `protobuf:"varint,16,opt,name=list_state,json=listState,proto3,enum=articles.v1.ArticleListState" json:"list_state,omitempty"`
	IsFavorite       bool              `protobuf:"varint,17,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{3}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Article) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Article) GetExtractedHtml() string {
	if x != nil {
		return x.ExtractedHtml
	}
	return ""
}

func (x *Article) GetPureText() string {
	if x != nil {
		return x.PureText
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Article) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Article) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *Article) GetPhonemizerData() []*PhonemizerData {
	if x != nil {
		return x.PhonemizerData
	}
	return nil
}

func (x *Article) GetPlayerPositionMs() int64 {
	if x != nil {
		return x.PlayerPositionMs
	}
	return 0
}

func (x *Article) GetScrollPosition() float64 {
	if x != nil {
		return x.ScrollPosition
	}
	return 0
}

func (x *Article) GetPlaybackSpeed() float64 {
	if x != nil {
		return x.PlaybackSpeed
	}
	return 0
}

func (x *Article) GetListState() ArticleListState {
	if x != nil {
		return x.ListState
	}
	return ArticleListState_ARTICLE_LIST_STATE_UNSPECIFIED
}

func (x *Article) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

type GetArticlesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filters
	Categories  []string `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	SearchQuery *string  `protobuf:"bytes,4,opt,name=search_query,json=searchQuery,proto3,oneof" json:"search_query,omitempty"`
	Author      *string  `protobuf:"bytes,5,opt,name=author,proto3,oneof" json:"author,omitempty"`
	// Which list to fetch. Unspecified defaults to inbox.
	View          ArticleView `protobuf:"varint,6,opt,name=view,proto3,enum=articles.v1.ArticleView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesRequest) Reset() {
	*x = GetArticlesRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesRequest) ProtoMessage() {}

func (x *GetArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetArticlesRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticlesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetArticlesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetArticlesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetArticlesRequest) GetSearchQuery() string {
	if x != nil && x.SearchQuery != nil {
		return *x.SearchQuery
	}
	return ""
}

func (x *GetArticlesRequest) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *GetArticlesRequest) GetView() ArticleView {
	if x != nil {
		return x.View
	}
	return ArticleView_ARTICLE_VIEW_UNSPECIFIED
}

type GetArticlesResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Articles []*ArticlePreview      `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	// Token for the cursor based pagination
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of articles matching the query
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesResponse) Reset() {
	*x = GetArticlesResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesResponse) ProtoMessage() {}

func (x *GetArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetArticlesResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetArticlesResponse) GetArticles() []*ArticlePreview {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *GetArticlesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetArticlesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ParseArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseArticleRequest) Reset() {
	*x = ParseArticleRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseArticleRequest) ProtoMessage() {}

func (x *ParseArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseArticleRequest.ProtoReflect.Descriptor instead.
func (*ParseArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{8}
}

func (x *ParseArticleRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ParseArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseArticleResponse) Reset() {
	*x = ParseArticleResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseArticleResponse) ProtoMessage() {}

func (x *ParseArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseArticleResponse.ProtoReflect.Descriptor instead.
func (*ParseArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{9}
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{11}
}

// Moves an article between lists and/or toggles its favorite flag. Only the
// provided fields are changed, so list_state and is_favorite can be updated
// independently.
type SetArticleStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ListState     *ArticleListState      `protobuf:"varint,2,opt,name=list_state,json=listState,proto3,enum=articles.v1.ArticleListState,oneof" json:"list_state,omitempty"`
	IsFavorite    *bool                  `protobuf:"varint,3,opt,name=is_favorite,json=isFavorite,proto3,oneof" json:"is_favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetArticleStateRequest) Reset() {
	*x = SetArticleStateRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetArticleStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArticleStateRequest) ProtoMessage() {}

func (x *SetArticleStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetArticleStateRequest.ProtoReflect.Descriptor instead.
func (*SetArticleStateRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{12}
}

func (x *SetArticleStateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetArticleStateRequest) GetListState() ArticleListState {
	if x != nil && x.ListState != nil {
		return *x.ListState
	}
	return ArticleListState_ARTICLE_LIST_STATE_UNSPECIFIED
}

func (x *SetArticleStateRequest) GetIsFavorite() bool {
	if x != nil && x.IsFavorite != nil {
		return *x.IsFavorite
	}
	return false
}

type SetArticleStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetArticleStateResponse) Reset() {
	*x = SetArticleStateResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetArticleStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArticleStateResponse) ProtoMessage() {}

func (x *SetArticleStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetArticleStateResponse.ProtoReflect.Descriptor instead.
func (*SetArticleStateResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{13}
}

type SaveArticleProgressRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ArticleId        string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	PlayerPositionMs int64                  `protobuf:"varint,2,opt,name=player_position_ms,json=playerPositionMs,proto3" json:"player_position_ms,omitempty"`
	ScrollPosition   float64                `protobuf:"fixed64,3,opt,name=scroll_position,json=scrollPosition,proto3" json:"scroll_position,omitempty"`
	PlaybackSpeed    float64                `protobuf:"fixed64,4,opt,name=playback_speed,json=playbackSpeed,proto3" json:"playback_speed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SaveArticleProgressRequest) Reset() {
	*x = SaveArticleProgressRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveArticleProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveArticleProgressRequest) ProtoMessage() {}

func (x *SaveArticleProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveArticleProgressRequest.ProtoReflect.Descriptor instead.
func (*SaveArticleProgressRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{14}
}

func (x *SaveArticleProgressRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *SaveArticleProgressRequest) GetPlayerPositionMs() int64 {
	if x != nil {
		return x.PlayerPositionMs
	}
	return 0
}

func (x *SaveArticleProgressRequest) GetScrollPosition() float64 {
	if x != nil {
		return x.ScrollPosition
	}
	return 0
}

func (x *SaveArticleProgressRequest) GetPlaybackSpeed() float64 {
	if x != nil {
		return x.PlaybackSpeed
	}
	return 0
}

type SaveArticleProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveArticleProgressResponse) Reset() {
	*x = SaveArticleProgressResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveArticleProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveArticleProgressResponse) ProtoMessage() {}

func (x *SaveArticleProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveArticleProgressResponse.ProtoReflect.Descriptor instead.
func (*SaveArticleProgressResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{15}
}

type CheckForUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastCheckedAt int64                  `protobuf:"varint,1,opt,name=last_checked_at,json=lastCheckedAt,proto3" json:"last_checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckForUpdatesRequest) Reset() {
	*x = CheckForUpdatesRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdatesRequest) ProtoMessage() {}

func (x *CheckForUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdatesRequest.ProtoReflect.Descriptor instead.
func (*CheckForUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{16}
}

func (x *CheckForUpdatesRequest) GetLastCheckedAt() int64 {
	if x != nil {
		return x.LastCheckedAt
	}
	return 0
}

type CheckForUpdatesResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	HasUpdates bool                   `protobuf:"varint,1,opt,name=has_updates,json=hasUpdates,proto3" json:"has_updates,omitempty"`
	// Current server time - use this as next last_checked_at
	ServerTimestamp int64 `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckForUpdatesResponse) Reset() {
	*x = CheckForUpdatesResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdatesResponse) ProtoMessage() {}

func (x *CheckForUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdatesResponse.ProtoReflect.Descriptor instead.
func (*CheckForUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{17}
}

func (x *CheckForUpdatesResponse) GetHasUpdates() bool {
	if x != nil {
		return x.HasUpdates
	}
	return false
}

func (x *CheckForUpdatesResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

type StreamArticleUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamArticleUpdatesRequest) Reset() {
	*x = StreamArticleUpdatesRequest{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamArticleUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamArticleUpdatesRequest) ProtoMessage() {}

func (x *StreamArticleUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamArticleUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamArticleUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{18}
}

type StreamArticleUpdatesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Article *ArticlePreview        `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	// "updated" | "heartbeat"
	EventType     string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamArticleUpdatesResponse) Reset() {
	*x = StreamArticleUpdatesResponse{}
	mi := &file_articles_v1_articles_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamArticleUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamArticleUpdatesResponse) ProtoMessage() {}

func (x *StreamArticleUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_articles_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamArticleUpdatesResponse.ProtoReflect.Descriptor instead.
func (*StreamArticleUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_articles_service_proto_rawDescGZIP(), []int{19}
}

func (x *StreamArticleUpdatesResponse) GetArticle() *ArticlePreview {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *StreamArticleUpdatesResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

var File_articles_v1_articles_service_proto protoreflect.FileDescriptor

const file_articles_v1_articles_service_proto_rawDesc = "" +
	"\n" +
	"\"articles/v1/articles_service.proto\x12\varticles.v1\"q\n" +
	"\x13PhonemizerTokenMeta\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vphoneme_len\x18\x02 \x01(\rR\n" +
	"phonemeLen\x12%\n" +
	"\x0ehas_whitespace\x18\x03 \x01(\bR\rhasWhitespace\"\xa8\x01\n" +
	"\x0ePhonemizerData\x12\x1c\n" +
	"\tgraphemes\x18\x01 \x01(\tR\tgraphemes\x12\x1a\n" +
	"\bphonemes\x18\x02 \x01(\tR\bphonemes\x12\x1b\n" +
	"\ttoken_ids\x18\x03 \x03(\x03R\btokenIds\x12?\n" +
	"\n" +
	"token_meta\x18\x04 \x03(\v2 .articles.v1.PhonemizerTokenMetaR\ttokenMeta\"\xbe\x03\n" +
	"\x0eArticlePreview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12%\n" +
	"\vdescription\x18\b \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\t \x01(\tH\x01R\x05image\x88\x01\x01\x12,\n" +
	"\x12player_position_ms\x18\n" +
	" \x01(\x03R\x10playerPositionMs\x12'\n" +
	"\x0fscroll_position\x18\v \x01(\x01R\x0escrollPosition\x12<\n" +
	"\n" +
	"list_state\x18\f \x01(\x0e2\x1d.articles.v1.ArticleListStateR\tlistState\x12\x1f\n" +
	"\vis_favorite\x18\r \x01(\bR\n" +
	"isFavoriteB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_image\"\xe8\x04\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12%\n" +
	"\x0eextracted_html\x18\x06 \x01(\tR\rextractedHtml\x12\x1b\n" +
	"\tpure_text\x18\a \x01(\tR\bpureText\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"categories\x18\t \x03(\tR\n" +
	"categories\x12%\n" +
	"\vdescription\x18\n" +
	" \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\v \x01(\tH\x01R\x05image\x88\x01\x01\x12D\n" +
	"\x0fphonemizer_data\x18\f \x03(\v2\x1b.articles.v1.PhonemizerDataR\x0ephonemizerData\x12,\n" +
	"\x12player_position_ms\x18\r \x01(\x03R\x10playerPositionMs\x12'\n" +
	"\x0fscroll_position\x18\x0e \x01(\x01R\x0escrollPosition\x12%\n" +
	"\x0eplayback_speed\x18\x0f \x01(\x01R\rplaybackSpeed\x12<\n" +
	"\n" +
	"list_state\x18\x10 \x01(\x0e2\x1d.articles.v1.ArticleListStateR\tlistState\x12\x1f\n" +
	"\vis_favorite\x18\x11 \x01(\bR\n" +
	"isFavoriteB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_image\"\xff\x01\n" +
	"\x12GetArticlesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12&\n" +
	"\fsearch_query\x18\x04 \x01(\tH\x00R\vsearchQuery\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x05 \x01(\tH\x01R\x06author\x88\x01\x01\x12,\n" +
	"\x04view\x18\x06 \x01(\x0e2\x18.articles.v1.ArticleViewR\x04viewB\x0f\n" +
	"\r_search_queryB\t\n" +
	"\a_author\"\x97\x01\n" +
	"\x13GetArticlesResponse\x127\n" +
	"\barticles\x18\x01 \x03(\v2\x1b.articles.v1.ArticlePreviewR\barticles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x12GetArticleResponse\x12.\n" +
	"\aarticle\x18\x01 \x01(\v2\x14.articles.v1.ArticleR\aarticle\"'\n" +
	"\x13ParseArticleRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x16\n" +
	"\x14ParseArticleResponse\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteArticleResponse\"\xb0\x01\n" +
	"\x16SetArticleStateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\n" +
	"list_state\x18\x02 \x01(\x0e2\x1d.articles.v1.ArticleListStateH\x00R\tlistState\x88\x01\x01\x12$\n" +
	"\vis_favorite\x18\x03 \x01(\bH\x01R\n" +
	"isFavorite\x88\x01\x01B\r\n" +
	"\v_list_stateB\x0e\n" +
	"\f_is_favorite\"\x19\n" +
	"\x17SetArticleStateResponse\"\xb9\x01\n" +
	"\x1aSaveArticleProgressRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12,\n" +
	"\x12player_position_ms\x18\x02 \x01(\x03R\x10playerPositionMs\x12'\n" +
	"\x0fscroll_position\x18\x03 \x01(\x01R\x0escrollPosition\x12%\n" +
	"\x0eplayback_speed\x18\x04 \x01(\x01R\rplaybackSpeed\"\x1d\n" +
	"\x1bSaveArticleProgressResponse\"@\n" +
	"\x16CheckForUpdatesRequest\x12&\n" +
	"\x0flast_checked_at\x18\x01 \x01(\x03R\rlastCheckedAt\"e\n" +
	"\x17CheckForUpdatesResponse\x12\x1f\n" +
	"\vhas_updates\x18\x01 \x01(\bR\n" +
	"hasUpdates\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\"\x1d\n" +
	"\x1bStreamArticleUpdatesRequest\"t\n" +
	"\x1cStreamArticleUpdatesResponse\x125\n" +
	"\aarticle\x18\x01 \x01(\v2\x1b.articles.v1.ArticlePreviewR\aarticle\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType*t\n" +
	"\x10ArticleListState\x12\"\n" +
	"\x1eARTICLE_LIST_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ARTICLE_LIST_STATE_INBOX\x10\x01\x12\x1e\n" +
	"\x1aARTICLE_LIST_STATE_ARCHIVE\x10\x02*x\n" +
	"\vArticleView\x12\x1c\n" +
	"\x18ARTICLE_VIEW_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ARTICLE_VIEW_INBOX\x10\x01\x12\x19\n" +
	"\x15ARTICLE_VIEW_FAVORITE\x10\x02\x12\x18\n" +
	"\x14ARTICLE_VIEW_ARCHIVE\x10\x032\xf4\x05\n" +
	"\x0fArticlesService\x12S\n" +
	"\fParseArticle\x12 .articles.v1.ParseArticleRequest\x1a!.articles.v1.ParseArticleResponse\x12P\n" +
	"\vGetArticles\x12\x1f.articles.v1.GetArticlesRequest\x1a .articles.v1.GetArticlesResponse\x12M\n" +
	"\n" +
	"GetArticle\x12\x1e.articles.v1.GetArticleRequest\x1a\x1f.articles.v1.GetArticleResponse\x12V\n" +
	"\rDeleteArticle\x12!.articles.v1.DeleteArticleRequest\x1a\".articles.v1.DeleteArticleResponse\x12\\\n" +
	"\x0fSetArticleState\x12#.articles.v1.SetArticleStateRequest\x1a$.articles.v1.SetArticleStateResponse\x12\\\n" +
	"\x0fCheckForUpdates\x12#.articles.v1.CheckForUpdatesRequest\x1a$.articles.v1.CheckForUpdatesResponse\x12h\n" +
	"\x13SaveArticleProgress\x12'.articles.v1.SaveArticleProgressRequest\x1a(.articles.v1.SaveArticleProgressResponse\x12m\n" +
	"\x14StreamArticleUpdates\x12(.articles.v1.StreamArticleUpdatesRequest\x1a).articles.v1.StreamArticleUpdatesResponse0\x01BGZEgithub.com/gogotchuri/readintent/backend/proto/articles/v1;articlesv1b\x06proto3"

var (
	file_articles_v1_articles_service_proto_rawDescOnce sync.Once
	file_articles_v1_articles_service_proto_rawDescData []byte
)

func file_articles_v1_articles_service_proto_rawDescGZIP() []byte {
	file_articles_v1_articles_service_proto_rawDescOnce.Do(func() {
		file_articles_v1_articles_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articles_v1_articles_service_proto_rawDesc), len(file_articles_v1_articles_service_proto_rawDesc)))
	})
	return file_articles_v1_articles_service_proto_rawDescData
}

var file_articles_v1_articles_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_articles_v1_articles_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_articles_v1_articles_service_proto_goTypes = []any{
	(ArticleListState)(0),                // 0: articles.v1.ArticleListState
	(ArticleView)(0),                     // 1: articles.v1.ArticleView
	(*PhonemizerTokenMeta)(nil),          // 2: articles.v1.PhonemizerTokenMeta
	(*PhonemizerData)(nil),               // 3: articles.v1.PhonemizerData
	(*ArticlePreview)(nil),               // 4: articles.v1.ArticlePreview
	(*Article)(nil),                      // 5: articles.v1.Article
	(*GetArticlesRequest)(nil),           // 6: articles.v1.GetArticlesRequest
	(*GetArticlesResponse)(nil),          // 7: articles.v1.GetArticlesResponse
	(*GetArticleRequest)(nil),            // 8: articles.v1.GetArticleRequest
	(*GetArticleResponse)(nil),           // 9: articles.v1.GetArticleResponse
	(*ParseArticleRequest)(nil),          // 10: articles.v1.ParseArticleRequest
	(*ParseArticleResponse)(nil),         // 11: articles.v1.ParseArticleResponse
	(*DeleteArticleRequest)(nil),         // 12: articles.v1.DeleteArticleRequest
	(*DeleteArticleResponse)(nil),        // 13: articles.v1.DeleteArticleResponse
	(*SetArticleStateRequest)(nil),       // 14: articles.v1.SetArticleStateRequest
	(*SetArticleStateResponse)(nil),      // 15: articles.v1.SetArticleStateResponse
	(*SaveArticleProgressRequest)(nil),   // 16: articles.v1.SaveArticleProgressRequest
	(*SaveArticleProgressResponse)(nil),  // 17: articles.v1.SaveArticleProgressResponse
	(*CheckForUpdatesRequest)(nil),       // 18: articles.v1.CheckForUpdatesRequest
	(*CheckForUpdatesResponse)(nil),      // 19: articles.v1.CheckForUpdatesResponse
	(*StreamArticleUpdatesRequest)(nil),  // 20: articles.v1.StreamArticleUpdatesRequest
	(*StreamArticleUpdatesResponse)(nil), // 21: articles.v1.StreamArticleUpdatesResponse
}
var file_articles_v1_articles_service_proto_depIdxs = []int32{
	2,  // 0: articles.v1.PhonemizerData.token_meta:type_name -> articles.v1.PhonemizerTokenMeta
	0,  // 1: articles.v1.ArticlePreview.list_state:type_name -> articles.v1.ArticleListState
	3,  // 2: articles.v1.Article.phonemizer_data:type_name -> articles.v1.PhonemizerData
	0,  // 3: articles.v1.Article.list_state:type_name -> articles.v1.ArticleListState
	1,  // 4: articles.v1.GetArticlesRequest.view:type_name -> articles.v1.ArticleView
	4,  // 5: articles.v1.GetArticlesResponse.articles:type_name -> articles.v1.ArticlePreview
	5,  // 6: articles.v1.GetArticleResponse.article:type_name -> articles.v1.Article
	0,  // 7: articles.v1.SetArticleStateRequest.list_state:type_name -> articles.v1.ArticleListState
	4,  // 8: articles.v1.StreamArticleUpdatesResponse.article:type_name -> articles.v1.ArticlePreview
	10, // 9: articles.v1.ArticlesService.ParseArticle:input_type -> articles.v1.ParseArticleRequest
	6,  // 10: articles.v1.ArticlesService.GetArticles:input_type -> articles.v1.GetArticlesRequest
	8,  // 11: articles.v1.ArticlesService.GetArticle:input_type -> articles.v1.GetArticleRequest
	12, // 12: articles.v1.ArticlesService.DeleteArticle:input_type -> articles.v1.DeleteArticleRequest
	14, // 13: articles.v1.ArticlesService.SetArticleState:input_type -> articles.v1.SetArticleStateRequest
	18, // 14: articles.v1.ArticlesService.CheckForUpdates:input_type -> articles.v1.CheckForUpdatesRequest
	16, // 15: articles.v1.ArticlesService.SaveArticleProgress:input_type -> articles.v1.SaveArticleProgressRequest
	20, // 16: articles.v1.ArticlesService.StreamArticleUpdates:input_type -> articles.v1.StreamArticleUpdatesRequest
	11, // 17: articles.v1.ArticlesService.ParseArticle:output_type -> articles.v1.ParseArticleResponse
	7,  // 18: articles.v1.ArticlesService.GetArticles:output_type -> articles.v1.GetArticlesResponse
	9,  // 19: articles.v1.ArticlesService.GetArticle:output_type -> articles.v1.GetArticleResponse
	13, // 20: articles.v1.ArticlesService.DeleteArticle:output_type -> articles.v1.DeleteArticleResponse
	15, // 21: articles.v1.ArticlesService.SetArticleState:output_type -> articles.v1.SetArticleStateResponse
	19, // 22: articles.v1.ArticlesService.CheckForUpdates:output_type -> articles.v1.CheckForUpdatesResponse
	17, // 23: articles.v1.ArticlesService.SaveArticleProgress:output_type -> articles.v1.SaveArticleProgressResponse
	21, // 24: articles.v1.ArticlesService.StreamArticleUpdates:output_type -> articles.v1.StreamArticleUpdatesResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_articles_v1_articles_service_proto_init() }
func file_articles_v1_articles_service_proto_init() {
	if File_articles_v1_articles_service_proto != nil {
		return
	}
	file_articles_v1_articles_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_articles_v1_articles_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_articles_v1_articles_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_articles_v1_articles_service_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articles_v1_articles_service_proto_rawDesc), len(file_articles_v1_articles_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_articles_v1_articles_service_proto_goTypes,
		DependencyIndexes: file_articles_v1_articles_service_proto_depIdxs,
		EnumInfos:         file_articles_v1_articles_service_proto_enumTypes,
		MessageInfos:      file_articles_v1_articles_service_proto_msgTypes,
	}.Build()
	File_articles_v1_articles_service_proto = out.File
	file_articles_v1_articles_service_proto_goTypes = nil
	file_articles_v1_articles_service_proto_depIdxs = nil
}
