import { sessionStorage } from "./browser_apis.js";

const API_URL = "http://localhost:8081";

/**
 * Given a async function, returns tuple of [response, error] (Go style)
 * If and only if the promise throws an error we return non-null error. It is not guaranteed that promise result will be non-null
 * This is for convenience and for not increasing cyclomatic complexity unnecessarily (Also because I prefer errors as values as opposed to exceptions)
 * @param {Promise} promise
 */
async function tryAsync(promise) {
  try {
    return [await promise, null];
  } catch (e) {
    const err = e instanceof Error ? e : new Error(String(e));
    return [null, err];
  }
}

/**
 * Make authenticated request against the API
 * convenience method wrapping fetch and adding session token
 * @param {"POST"|"GET"} method
 * @param {string} uri of request endpoint, include initial /
 * @param {Object} request body
 * @returns {Promise<any>}
 */
async function authenticatedRequest(method, uri, body = undefined) {
  const [token, err] = await sessionStorage.getSessionToken();
  if (err) {
    throw err;
  }
  const requestBody = method === "GET" ? undefined : JSON.stringify(body);
  const res = await fetch(`${API_URL}${uri}`, {
    method: method,
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: requestBody,
  });
  if (!res.ok) {
    throw new Error(`request failed: ${res.status}`);
  }
  return await res.json();
}

async function request(method, uri, body = undefined) {
  const requestBody = method === "GET" ? undefined : JSON.stringify(body);
  const res = await fetch(`${API_URL}${uri}`, {
    method: method,
    headers: {
      "Content-Type": "application/json",
    },
    body: requestBody,
  });
  if (!res.ok) {
    throw new Error(`request failed: ${res.status}`);
  }
  return await res.json();
}

// ========== Public endpoints ============

/**
 * requestCodes is the first step in the process of "Authorization Grant". We request device and user verification codes from the server
 * returns error as the second tuple item or in case of success the object described as the first one
 * **Note** interval is in seconds and the interval of 5 seconds should be used by default
 * @returns {Promise<[{device_code: string, user_code: string, expires_in: number, interval: number}, Error|null]>}
 */
export async function requestCodes() {
  const [res, err] = await tryAsync(
    request("GET", `/extension/pairing/request-codes`),
  );
  if (err) {
    return [null, err];
  }
  return [res, null];
}

/**
 * Check the pairing status of the device. This endpoint should be used for polling.\
 * Returns error in case of any failure. This is a safe case to ignore and continue polling.
 * Otherwise always returns status in the result. The status will either be
 *  - "pending": In which case polling should continue
 *  - "expired": The extension must stop polling and re-request codes
 *  - "paired": The extension must stop polling, mark itself as authenticated  and use the returned session token for authenticated requests
 * @param {string} deviceID generated by server
 * @returns {Promise<[{session_token: string, status: "paired"} | {status: "expired"|"pending"}, Error|null]>}
 */
export async function checkPairingStatus(deviceID) {
  const [res, err] = await tryAsync(
    request("GET", `/extension/pairing/status?device_id=${deviceID}`),
  );
  if (err) {
    return [null, err];
  }
  return [res, null];
}
// =========== Authenticated endpoints =========

/**
 * Submit article to API, html can be omitted, in which case the scraper service will try to scrape the url
 * **NOTE** Keep in mind that for articles behind paywall the scraper service won't be able to extract a complete article
 *  without rendered HTML passed here
 * @param {{url: string, html: string|undefined}} article URL and HTML to submit for parsing
 * @returns {Promise<Error|null>} Return null in case of success otherwise error
 */
export async function submitArticle({ url, html }) {
  const body = { url, html };

  const [_, err] = await tryAsync(
    authenticatedRequest("POST", "/extension/submit-article", body),
  );
  return err;
}
