// Mocks generated by Mockito 5.4.6 from annotations
// in readintent_flutter/test/articles/api/articles_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:readintent_flutter/features/articles/api/articles_service_client.dart'
    as _i3;
import 'package:readintent_flutter/proto/articles/v1/articles_service.pb.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetArticlesResponse_0 extends _i1.SmartFake
    implements _i2.GetArticlesResponse {
  _FakeGetArticlesResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetArticleResponse_1 extends _i1.SmartFake
    implements _i2.GetArticleResponse {
  _FakeGetArticleResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeParseArticleResponse_2 extends _i1.SmartFake
    implements _i2.ParseArticleResponse {
  _FakeParseArticleResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteArticleResponse_3 extends _i1.SmartFake
    implements _i2.DeleteArticleResponse {
  _FakeDeleteArticleResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCheckForUpdatesResponse_4 extends _i1.SmartFake
    implements _i2.CheckForUpdatesResponse {
  _FakeCheckForUpdatesResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveArticleProgressResponse_5 extends _i1.SmartFake
    implements _i2.SaveArticleProgressResponse {
  _FakeSaveArticleProgressResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ArticlesServiceClientI].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesServiceClientI extends _i1.Mock
    implements _i3.ArticlesServiceClientI {
  MockArticlesServiceClientI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GetArticlesResponse> getArticles(
    _i2.GetArticlesRequest? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getArticles, [input]),
            returnValue: _i4.Future<_i2.GetArticlesResponse>.value(
              _FakeGetArticlesResponse_0(
                this,
                Invocation.method(#getArticles, [input]),
              ),
            ),
          )
          as _i4.Future<_i2.GetArticlesResponse>);

  @override
  _i4.Future<_i2.GetArticleResponse> getArticle(_i2.GetArticleRequest? input) =>
      (super.noSuchMethod(
            Invocation.method(#getArticle, [input]),
            returnValue: _i4.Future<_i2.GetArticleResponse>.value(
              _FakeGetArticleResponse_1(
                this,
                Invocation.method(#getArticle, [input]),
              ),
            ),
          )
          as _i4.Future<_i2.GetArticleResponse>);

  @override
  _i4.Future<_i2.ParseArticleResponse> parseArticle(
    _i2.ParseArticleRequest? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseArticle, [input]),
            returnValue: _i4.Future<_i2.ParseArticleResponse>.value(
              _FakeParseArticleResponse_2(
                this,
                Invocation.method(#parseArticle, [input]),
              ),
            ),
          )
          as _i4.Future<_i2.ParseArticleResponse>);

  @override
  _i4.Future<_i2.DeleteArticleResponse> deleteArticle(
    _i2.DeleteArticleRequest? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteArticle, [input]),
            returnValue: _i4.Future<_i2.DeleteArticleResponse>.value(
              _FakeDeleteArticleResponse_3(
                this,
                Invocation.method(#deleteArticle, [input]),
              ),
            ),
          )
          as _i4.Future<_i2.DeleteArticleResponse>);

  @override
  _i4.Future<_i2.CheckForUpdatesResponse> checkForUpdates(
    _i2.CheckForUpdatesRequest? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkForUpdates, [input]),
            returnValue: _i4.Future<_i2.CheckForUpdatesResponse>.value(
              _FakeCheckForUpdatesResponse_4(
                this,
                Invocation.method(#checkForUpdates, [input]),
              ),
            ),
          )
          as _i4.Future<_i2.CheckForUpdatesResponse>);

  @override
  _i4.Future<_i2.SaveArticleProgressResponse> saveArticleProgress(
    _i2.SaveArticleProgressRequest? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveArticleProgress, [input]),
            returnValue: _i4.Future<_i2.SaveArticleProgressResponse>.value(
              _FakeSaveArticleProgressResponse_5(
                this,
                Invocation.method(#saveArticleProgress, [input]),
              ),
            ),
          )
          as _i4.Future<_i2.SaveArticleProgressResponse>);

  @override
  _i4.Stream<_i2.StreamArticleUpdatesResponse> streamArticleUpdates(
    _i2.StreamArticleUpdatesRequest? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamArticleUpdates, [input]),
            returnValue: _i4.Stream<_i2.StreamArticleUpdatesResponse>.empty(),
          )
          as _i4.Stream<_i2.StreamArticleUpdatesResponse>);
}
