// Mocks generated by Mockito 5.4.6 from annotations
// in readintent_flutter/test/auth/presentation/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:readintent_flutter/core/session_storage.dart' as _i4;
import 'package:readintent_flutter/features/auth/api/auth_client.dart' as _i2;
import 'package:readintent_flutter/models/user.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSession_0 extends _i1.SmartFake implements _i2.Session {
  _FakeSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthClient extends _i1.Mock implements _i2.AuthClient {
  MockAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> Function() get onUnauthorized =>
      (super.noSuchMethod(
            Invocation.getter(#onUnauthorized),
            returnValue: () => _i3.Future<void>.value(),
          )
          as _i3.Future<void> Function());

  @override
  _i3.Future<_i2.Session> getSession() =>
      (super.noSuchMethod(
            Invocation.method(#getSession, []),
            returnValue: _i3.Future<_i2.Session>.value(
              _FakeSession_0(this, Invocation.method(#getSession, [])),
            ),
          )
          as _i3.Future<_i2.Session>);

  @override
  _i3.Future<void> claimGrantCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#claimGrantCode, [code]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.Session> passwordLogin(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#passwordLogin, [email, password]),
            returnValue: _i3.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#passwordLogin, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i2.Session>);

  @override
  _i3.Future<_i2.Session> passwordRegistration(
    String? email,
    String? password,
    String? firstName,
    String? lastName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#passwordRegistration, [
              email,
              password,
              firstName,
              lastName,
            ]),
            returnValue: _i3.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#passwordRegistration, [
                  email,
                  password,
                  firstName,
                  lastName,
                ]),
              ),
            ),
          )
          as _i3.Future<_i2.Session>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SessionStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionStorage extends _i1.Mock implements _i4.SessionStorage {
  MockSessionStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.User?> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i3.Future<_i5.User?>.value(),
          )
          as _i3.Future<_i5.User?>);

  @override
  _i3.Future<void> saveUser(_i5.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
