// Mocks generated by Mockito 5.4.6 from annotations
// in readintent_flutter/test/articles/presentation/article_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:readintent_flutter/features/articles/api/articles_client.dart'
    as _i3;
import 'package:readintent_flutter/proto/articles/v1/articles_service.pb.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetArticlesResponse_0 extends _i1.SmartFake
    implements _i2.GetArticlesResponse {
  _FakeGetArticlesResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArticle_1 extends _i1.SmartFake implements _i2.Article {
  _FakeArticle_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ArticlesClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesClient extends _i1.Mock implements _i3.ArticlesClient {
  MockArticlesClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GetArticlesResponse> getArticles({
    int? pageSize = 20,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getArticles, [], {
              #pageSize: pageSize,
              #pageToken: pageToken,
            }),
            returnValue: _i4.Future<_i2.GetArticlesResponse>.value(
              _FakeGetArticlesResponse_0(
                this,
                Invocation.method(#getArticles, [], {
                  #pageSize: pageSize,
                  #pageToken: pageToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.GetArticlesResponse>);

  @override
  _i4.Future<void> parseArticle(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#parseArticle, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Article> getArticle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getArticle, [id]),
            returnValue: _i4.Future<_i2.Article>.value(
              _FakeArticle_1(this, Invocation.method(#getArticle, [id])),
            ),
          )
          as _i4.Future<_i2.Article>);

  @override
  _i4.Future<void> deleteArticle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteArticle, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
