#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER kratos WITH PASSWORD '$KRATOS_POSTGRES_PASSWORD';
    CREATE USER bff WITH PASSWORD '$BFF_POSTGRES_PASSWORD';
EOSQL