#ENC[AES256_GCM,data:dw6HM1typqp2SpW/gdzkut6GTVOmERFmlIhiCSyMjC6yNvA+ZKHDWj4XKZ8TDt/71FPi+rvglCKqaZgj0oG6mTGrRoTV+fZHs70+Y68ui+FMd2/6+G3aRqmXzI8=,iv:vMYAwSfGyNuJObYo7wutocrhh5DxrpbHY+wuKuOcbP0=,tag:3gvC2SbyDWRRBvq9FiNrmw==,type:comment]
#ENC[AES256_GCM,data:y7TiMVRCYawIYDYc4tlruNhdAaYpufMl1qbT21SaS5/s8WHhD9FF/zXcmvEOdVsz5nRH9eDj8LsvcLM7icDeAdvnhgOAREGYGcqikw==,iv:rgtzYj5EjmdefhoqPY8mMgyJdFh5m5wM0Q7x+jdZm0o=,tag:kI/6zuy3sKjHlusPdneIRA==,type:comment]
postgres_password: ENC[AES256_GCM,data:0DAftUin/237iU5cxR7Uctcscp7PPxXm9T8bhupfels=,iv:fVhpnvgXcUzSeF0JGTsfZfpZlX+belottJeUYmACwNE=,tag:lcwY0CY9qUYtyI3hf82X3Q==,type:str]
postgres_user: ENC[AES256_GCM,data:3FEs+gU=,iv:A69per+b2lPBhL6Xq+Dp5d+VoL8V8NUZYHZwKRzYQnU=,tag:Hiv6dVNHs3aPQTvrKG5wKg==,type:str]
postgres_db: ENC[AES256_GCM,data:LC2FY5PyMx3jO0D8zHRM,iv:osRXMqBU+dlC/ZHEJRMj6GFHs+52dnIgTn9q00kh1iY=,tag:G7h0TzGoXlb14RsaoqAfwQ==,type:str]
kratos_secret: ENC[AES256_GCM,data:rggCAwc1pEl58iKCRmkdTf5g4tdnUnAEBjkl+gp+sX0=,iv:bAEEWhHEQr/uIZiWbOPkVtgA2l5QxIIafXycPA5kHYg=,tag:8InRU+cqOyK0yI0+EdWiFg==,type:str]
kratos_cookie_secret: ENC[AES256_GCM,data:UhzAJhGb0DVt+dx0sjRBuGrIxiFHih+UD13IOLyxIGQ=,iv:vGKjO0QlPZF8GILS5Y9iyAg+UfgLTckm8v1HWXqQSRM=,tag:ArsWssUdZbCzhlG+XA13gA==,type:str]
bff_jwt_secret: ENC[AES256_GCM,data:PKNA0bAtctQrTvuuVnqmWt1ZsFN7D39sZ8/jYzanYYQ=,iv:ybEC7+y395Z6yJOCwq/tU5iv7CIuE7zVvFsNs8lF4Kc=,tag:8lFgy2VXNX+0ZRbdjmi0Mg==,type:str]
dockerhub_username: ENC[AES256_GCM,data:tnV4C7poyO/Btw==,iv:IvEU3wonzvHYC2GnO8g9jbsRhRvAdAyth2UtZSfcpG8=,tag:7Hp+6yf5hc+Vq3dlUhm6nA==,type:str]
dockerhub_token: ENC[AES256_GCM,data:jgQOsH9vQD3nmjZIzWAYW9BIV2DW9cex8ZdYiTIhfvOtTb+g,iv:wGjqouqECzogDrgdLMWPNDzdVKBuXTN2ssqMlcSezm8=,tag:5TVMqvwQB2CzhTnv+xe9Zg==,type:str]
google_oauth_client_id: ENC[AES256_GCM,data:h0wItlwBK5mOOKJ+hcR7/2hmvTvpjhcWIeDwthrPiimXN8womBWdXH0lk39qs/wOz3tep1h3LKg/RiWLIAym15xH/nRcg8SbZQ==,iv:Nb6oEcimuKVA7FW772tz/LzSYiG7iO7yQ+n/VoYWaNE=,tag:UHG1W+HgOLu2kPDh21AEDw==,type:str]
google_oauth_client_secret: ENC[AES256_GCM,data:caDpa4ADsVceRr6f60Xow50VESko5vnfeR0DDrXSUKSYP2w=,iv:JUpfpcJ5lMddbwxOBjHMQkY6gIKkvWFaLI0lGfOOTMk=,tag:SZaTnz+nfdb3MBpU758kLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU0d4Q0RVNFhrbVY5VE9F
            blZ0TFVBN09BWTdBcmhUc3hyMUhodnF4ZlgwCkJpNkNPeThmVDBZN1pvTTBVZFZv
            bjNDSG1Jcms2eEtnOTlJQTc3eUR2N2cKLS0tIHhPdzYxZUJ1MHoydmNNbG9vbTZI
            SG1QaWZ4SWZIb2hkSFd4RFl6ZkhPSmMKKLhS4XbyXTtLng2FxBei6R0o2eg0nmAN
            9scHoiJyiRkKvyuJiOGXW+p8a4uw8sYzwWIw4dvVAl27LpGoOxi1RQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13jxej9yf3wxxm0x75d3ms743rsukufygcm74smqws2m2tr5cfsnsjmlzwt
    lastmodified: "2026-05-27T12:49:12Z"
    mac: ENC[AES256_GCM,data:rVVhLMlD1jQxEFusTLptIwKjc4IIgV1UgqX6YyieN5ojd9oC0bKGGVW77kZxyLng72yGNmgd8UZsAlUQ9PbG7cvkXQvhIWmkSBTVj0Hrmges/5bpWCGdl+I+Db1nSvSIhDRPrPNPxrOWk/USkuynqqzrk+u3a4DkS+RdVVYroyU=,iv:A2wXhxzzPJYxiWeDWJeuAshMgoaDESuuQs+GZ/HkhcU=,tag:H8ZD/F24fBl5LVDqJ5kI5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
