// Mocks generated by Mockito 5.4.6 from annotations
// in readintent_flutter/test/auth/api/auth_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:readintent_flutter/features/auth/api/auth_service_client.dart'
    as _i3;
import 'package:readintent_flutter/proto/auth/v1/auth_service.pb.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePasswordLoginResponse_0 extends _i1.SmartFake
    implements _i2.PasswordLoginResponse {
  _FakePasswordLoginResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordRegistrationResponse_1 extends _i1.SmartFake
    implements _i2.PasswordRegistrationResponse {
  _FakePasswordRegistrationResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGetSessionResponse_2 extends _i1.SmartFake
    implements _i2.GetSessionResponse {
  _FakeGetSessionResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutResponse_3 extends _i1.SmartFake
    implements _i2.LogoutResponse {
  _FakeLogoutResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthResponse_4 extends _i1.SmartFake
    implements _i2.HealthResponse {
  _FakeHealthResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthServiceClientI].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthServiceClientI extends _i1.Mock
    implements _i3.AuthServiceClientI {
  MockAuthServiceClientI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PasswordLoginResponse> passwordLogin(
    _i2.PasswordLoginRequest? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#passwordLogin, [input]),
            returnValue: _i4.Future<_i2.PasswordLoginResponse>.value(
              _FakePasswordLoginResponse_0(
                this,
                Invocation.method(#passwordLogin, [input]),
              ),
            ),
          )
          as _i4.Future<_i2.PasswordLoginResponse>);

  @override
  _i4.Future<_i2.PasswordRegistrationResponse> passwordRegistration(
    _i2.PasswordRegistrationRequest? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#passwordRegistration, [input]),
            returnValue: _i4.Future<_i2.PasswordRegistrationResponse>.value(
              _FakePasswordRegistrationResponse_1(
                this,
                Invocation.method(#passwordRegistration, [input]),
              ),
            ),
          )
          as _i4.Future<_i2.PasswordRegistrationResponse>);

  @override
  _i4.Future<_i2.GetSessionResponse> getSession(_i2.GetSessionRequest? input) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [input]),
            returnValue: _i4.Future<_i2.GetSessionResponse>.value(
              _FakeGetSessionResponse_2(
                this,
                Invocation.method(#getSession, [input]),
              ),
            ),
          )
          as _i4.Future<_i2.GetSessionResponse>);

  @override
  _i4.Future<_i2.LogoutResponse> logout(_i2.LogoutRequest? input) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [input]),
            returnValue: _i4.Future<_i2.LogoutResponse>.value(
              _FakeLogoutResponse_3(this, Invocation.method(#logout, [input])),
            ),
          )
          as _i4.Future<_i2.LogoutResponse>);

  @override
  _i4.Future<_i2.HealthResponse> health(_i2.HealthRequest? input) =>
      (super.noSuchMethod(
            Invocation.method(#health, [input]),
            returnValue: _i4.Future<_i2.HealthResponse>.value(
              _FakeHealthResponse_4(this, Invocation.method(#health, [input])),
            ),
          )
          as _i4.Future<_i2.HealthResponse>);
}
